ARG CURRENTACCOUNTS_VERSION
FROM karimelnaggar/currentaccounts:${CURRENTACCOUNTS_VERSION}

COPY opentracing-specialagent-1.7.4.jar .

CMD ["sh", "-c", "java -javaagent:opentracing-specialagent-1.7.4.jar -jar currentaccounts-${CURRENTACCOUNTS_VERSION}.jar"]
