ARG CURRENTACCOUNTS_VERSION
FROM karimelnaggar/currentaccounts:${CURRENTACCOUNTS_VERSION}

COPY opentelemetry-javaagent-all.jar .

CMD ["sh", "-c", "java -javaagent:opentelemetry-javaagent-all.jar -jar currentaccounts-${CURRENTACCOUNTS_VERSION}.jar"]
