name: CI
on: push
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run build with Maven
        run: mvn -B install -P coverage --no-transfer-progress --file ./currentaccounts/pom.xml

      - name: Publish code coverage reports
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./jacoco.xml
          directory: ./**/target/site/jacoco/
          flags: unittests
          fail_ci_if_error: false
          verbose: true
